spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/noliter
    username: root
    password: root1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

logging:
  level:
    org.hibernate.type.descriptor.binding: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.SQL: DEBUG